name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rss -> target"
      - name: Build RSS
        run: |
          cd rss
          cargo run -- --data-path ../data ../static/feed.xml
      - name: Install Zola
        run: |
          wget -q -O zola.tar.gz "https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz"
          tar -xvf zola.tar.gz
      - name: Build website
        run: ./zola build
